{{- if eq .Values.proxyinjector.mount "configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "proxyinjector-name" . }}
    version: {{ .Chart.Version }}
    group: {{ .Values.proxyinjector.labels.group }}
    provider: {{ .Values.proxyinjector.labels.provider }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "proxyinjector-name" . }}
data:
{{ toYaml .Values.proxyinjector.data | indent 2 }}
{{- end }}