apiVersion: v1
name: proxyinjector
description: ProxyInjector chart that runs on kubernetes
version: 0.0.5
keywords:
  - Proxy
  - Authentication
  - kubernetes
home: https://github.com/stakater/ProxyInjector
maintainers:
- name: Stakater
  email: hello@stakater.com