kubernetes:
  host: https://kubernetes.default

proxyinjector:
  tolerations: {}
  labels:
    provider: stakater
    group: com.stakater.platform
    version: v0.0.10
  image:
    name: stakater/proxyinjector
    tag: "v0.0.10"
    pullPolicy: IfNotPresent
  watchGlobally: true
  configFilePath: /etc/ProxyInjector
  proxyconfig: |-
    enable-default-deny: true
    secure-cookie: false
    verbose: true
    enable-logging: true
    cors-origins:
    - '*'
    cors-methods:
    - GET
    - POST
    resources:
    - uri: '/'