kubernetes:
  host: https://kubernetes.default

proxyinjector:
  mount: "configmap"
  existingSecret: ""
  tolerations: {}
  labels:
    provider: stakater
    group: com.stakater.platform
    version: v0.0.22
  image:
    name: stakater/proxyinjector
    tag: "v0.0.22"
    pullPolicy: IfNotPresent
  watchGlobally: true
  configFilePath: /etc/ProxyInjector
  data:
    config.yml: |-
      proxyconfig:
        gatekeeper-image : "keycloak/keycloak-gatekeeper:6.0.1"
        enable-default-deny: true
        secure-cookie: false
        verbose: true
        enable-logging: true
        cors-origins:
        - '*'
        cors-methods:
        - GET
        - POST
        resources:
        - uri: '/*'
        scopes:
        - 'good-service'